services:
  my-service-web:
    image: 925047940866.dkr.ecr.ap-south-1.amazonaws.com/nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
    volumes:
      - /home/ec2-user/nginx/html:/usr/share/nginx/html:ro
    restart: always
    networks:
      - bridge-subnet
      
  fastapi-svc:
    image: 925047940866.dkr.ecr.ap-south-1.amazonaws.com/fastapi:latest
    container_name: fastapi-container
    ports:
      - "8000:8000"
    volumes:
      - /home/ec2-user/fastapi/app:/app:ro
    restart: always
    networks:
      - bridge-subnet

networks:
  bridge-subnet:
    driver: bridge
